name: "Stylelint Evaluator"
description: "Stylelint evaluator"
inputs:
  token:
    description: "The GitHub token to use for making API requests"
    required: true
  pr_number:
    description: 'Pull Request number that dispatched the workflow'
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
