name: "Stylelint Evaluator"
description: "Stylelint evaluator"
inputs:
  token:
    description: "The GitHub token to use for making API requests"
    required: true
  pr_number:
    description: 'Pull Request number that dispatched the workflow'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Stylelint Evaluator
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PR_NUMBER: ${{ inputs.pr_number }}